pipeline:
  publish:
    image: atomi/hugo:latest
    secrets: [ ssh_key ]
    commands:
      - env
      - eval $(ssh-agent);echo "$ssh_key" | ssh-add /dev/stdin;
      - git config --global user.name 'atomi'; git config --global user.email 'louiedog81@gmail.com'
      - git clone git@github.com:atomi/atomi.github.io.git public; hugo
      - cd public; touch .nojekyll; git add -A; git commit -am '${DRONE_COMMIT:0:10}'
      - git push -u origin master
  build_notification:
    image: plugins/gitter
    webhook: https://webhooks.gitter.im/e/9d079d14036a88e172a7
    when:
      status: [ success, failure ]
