baseurl: https://atomi.github.io/
theme: basic
DisableRSS: false
DisableSitemap: true
DisableHugoGeneratorInject: true
disable404: true
canonifyurls: false
permalinks:
        fixed: :title/

markup:
  highlight:
    noClasses: false

outputFormats:
  RSS:
    baseName: "rss"
