baseurl: https://atomi.github.io/
theme: basic
DisableRSS: true
DisableSitemap: true
DisableHugoGeneratorInject: true
disable404: true
canonifyurls: false
permalinks:
        fixed: :title/

markup:
  highlight:
    noClasses: false
